# Pandas & NumPy Practice Solutions

## Import Libraries

In [1]:

import pandas as pd
import numpy as np

## 1. Select rows where Age >= 31

In [2]:

data = {
'Name':['Teodosija','Sutton','Taneli','Ravshan','Ross'],
'Age':[26,32,25,31,28],
'Salary':[50000,60000,45000,70000,55000]
}

df = pd.DataFrame(data)

df[df['Age'] >= 31]

      Name  Age  Salary
1   Sutton   32   60000
3  Ravshan   31   70000

## 2. Age > 25 AND Salary > 50000

In [3]:

df[(df['Age'] > 25) & (df['Salary'] > 50000)]

      Name  Age  Salary
1   Sutton   32   60000
3  Ravshan   31   70000
4     Ross   28   55000

## 3. Remove Duplicate Rows

In [4]:

data = {
'Name':['Ross','Bob','Ross','Geoffrey','Bob'],
'Age':[25,30,25,22,30],
'Salary':[50000,60000,50000,45000,60000]
}

df = pd.DataFrame(data)

df.drop_duplicates()

       Name  Age  Salary
0      Ross   25   50000
1       Bob   30   60000
3  Geoffrey   22   45000

## 4. Reshape 1D NumPy Array to 2D

In [5]:

array_1d = np.array([1,2,3,4,5,6,7,8])

array_2d = array_1d.reshape(2,4)

array_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Data Selection with loc

In [6]:

df = pd.DataFrame({
'Product':['Laptop','Mouse','Keyboard','Monitor','Headphones'],
'Price':[999,25,75,300,150],
'Stock':[15,150,80,45,60],
'Category':['Electronics','Accessories','Accessories','Electronics','Audio']
}, index=['P001','P002','P003','P004','P005'])

df

         Product  Price  Stock     Category
P001      Laptop    999     15  Electronics
P002       Mouse     25    150  Accessories
P003    Keyboard     75     80  Accessories
P004     Monitor    300     45  Electronics
P005  Headphones    150     60        Audio

### 1. Select row P003

In [7]:

df.loc['P003']

Product        Keyboard
Price                75
Stock                80
Category    Accessories
Name: P003, dtype: object

### 2. Rows P002 to P004 with Product and Price

In [8]:

df.loc['P002':'P004', ['Product','Price']]

       Product  Price
P002     Mouse     25
P003  Keyboard     75
P004   Monitor    300

### 3. Category Electronics

In [9]:

df.loc[df['Category'] == 'Electronics']

      Product  Price  Stock     Category
P001   Laptop    999     15  Electronics
P004  Monitor    300     45  Electronics

## iloc Examples

### First 3 rows

In [10]:

df.iloc[:3]

       Product  Price  Stock     Category
P001    Laptop    999     15  Electronics
P002     Mouse     25    150  Accessories
P003  Keyboard     75     80  Accessories

### Rows at position 1 and 3

In [11]:

df.iloc[[1,3]]

      Product  Price  Stock     Category
P002    Mouse     25    150  Accessories
P004  Monitor    300     45  Electronics

### Last 2 rows and first 2 columns

In [12]:

df.iloc[-2:, :2]

         Product  Price
P004     Monitor    300
P005  Headphones    150

## Filtering with Conditions

In [13]:

df = pd.DataFrame({
'Name':['John','Sarah','Mike','Emma','Chris','Anna'],
'Department':['IT','HR','IT','Sales','Sales','HR'],
'Salary':[75000,65000,80000,55000,58000,62000],
'Years':[3,5,7,2,4,6],
'Remote':[True,False,True,False,True,False]
})

df

    Name Department  Salary  Years  Remote
0   John         IT   75000      3    True
1  Sarah         HR   65000      5   False
2   Mike         IT   80000      7    True
3   Emma      Sales   55000      2   False
4  Chris      Sales   58000      4    True
5   Anna         HR   62000      6   False

### Employees in IT

In [14]:

df[df['Department'] == 'IT']

   Name Department  Salary  Years  Remote
0  John         IT   75000      3    True
2  Mike         IT   80000      7    True

### Salary above 60000

In [15]:

df[df['Salary'] > 60000]

    Name Department  Salary  Years  Remote
0   John         IT   75000      3    True
1  Sarah         HR   65000      5   False
2   Mike         IT   80000      7    True
5   Anna         HR   62000      6   False

### Remote workers

In [16]:

df[df['Remote'] == True]

    Name Department  Salary  Years  Remote
0   John         IT   75000      3    True
2   Mike         IT   80000      7    True
4  Chris      Sales   58000      4    True

### Experience >= 5 years

In [17]:

df[df['Years'] >= 5]

    Name Department  Salary  Years  Remote
1  Sarah         HR   65000      5   False
2   Mike         IT   80000      7    True
5   Anna         HR   62000      6   False

## Mixed loc and iloc

In [18]:

df = pd.DataFrame({
'Name':['Alice','Bob','Carol','David','Eve'],
'Age':[25,30,35,28,32],
'City':['NYC','LA','Chicago','Houston','Phoenix'],
'Salary':[50000,60000,75000,55000,62000]
})

### Age > 28 then first 2 rows

In [19]:

df.loc[df['Age'] > 28].iloc[:2]

    Name  Age     City  Salary
1    Bob   30       LA   60000
2  Carol   35  Chicago   75000

### Salary of 3rd row

In [20]:

df.loc[2,'Salary']
df.iloc[2,3]

75000

## Multiple Conditions (AND)

In [21]:

df = pd.DataFrame({
'Name':['John','Sarah','Mike','Emma','Chris','Anna'],
'Department':['IT','HR','IT','Sales','Sales','HR'],
'Salary':[75000,65000,80000,55000,58000,62000],
'Years':[3,5,7,2,4,6],
'Remote':[True,False,True,False,True,False]
})

df[(df['Department']=='IT') & (df['Remote']==True)]

   Name Department  Salary  Years  Remote
0  John         IT   75000      3    True
2  Mike         IT   80000      7    True

In [22]:

df[(df['Salary'].between(60000,75000)) & (df['Years'] > 3)]

    Name Department  Salary  Years  Remote
1  Sarah         HR   65000      5   False
5   Anna         HR   62000      6   False

In [23]:

df[(df['Department']!='HR') & (df['Salary'] > 60000)]

   Name Department  Salary  Years  Remote
0  John         IT   75000      3    True
2  Mike         IT   80000      7    True

## Multiple Conditions (OR)

In [24]:

df[(df['Department']=='IT') | (df['Remote']==True)]

    Name Department  Salary  Years  Remote
0   John         IT   75000      3    True
2   Mike         IT   80000      7    True
4  Chris      Sales   58000      4    True

In [25]:

df[(df['Salary'] < 60000) | (df['Salary'] > 70000)]

    Name Department  Salary  Years  Remote
0   John         IT   75000      3    True
2   Mike         IT   80000      7    True
3   Emma      Sales   55000      2   False
4  Chris      Sales   58000      4    True

In [26]:

df[(df['Department']=='Sales') | (df['Years'] < 3)]

    Name Department  Salary  Years  Remote
3   Emma      Sales   55000      2   False
4  Chris      Sales   58000      4    True

## Complex Real-world Filtering

In [27]:

df = pd.DataFrame({
'Date': pd.date_range('2024-01-01', periods=10),
'Region':['North','South','East','West','North','South','East','West','North','South'],
'Product':['A','B','A','C','B','A','C','B','A','C'],
'Quantity':[10,15,8,20,12,25,18,22,14,30],
'Revenue':[1000,1500,800,2000,1200,2500,1800,2200,1400,3000]
})

In [28]:

df[(df['Region'].isin(['North','South'])) & (df['Revenue'] > 1200)]

        Date Region Product  Quantity  Revenue
1 2024-01-02  South       B        15     1500
5 2024-01-06  South       A        25     2500
8 2024-01-09  North       A        14     1400
9 2024-01-10  South       C        30     3000

In [29]:

df[(df['Product'].isin(['A','B'])) & (df['Quantity'].between(10,20))]

        Date Region Product  Quantity  Revenue
0 2024-01-01  North       A        10     1000
1 2024-01-02  South       B        15     1500
4 2024-01-05  North       B        12     1200
8 2024-01-09  North       A        14     1400

In [30]:

top50 = df['Revenue'].quantile(0.5)

df[(df['Region']!='West') & (df['Revenue'] >= top50)]

        Date Region Product  Quantity  Revenue
5 2024-01-06  South       A        25     2500
6 2024-01-07   East       C        18     1800
9 2024-01-10  South       C        30     3000