# Pandas Practice Problems

## Import Libraries

In [2]:
import pandas as pd
import numpy as np

## 1. Create DataFrame from Dictionary

In [3]:
data = {'X':[78,85,96,80,86],
        'Y':[84,94,89,83,86],
        'Z':[86,97,96,72,83]}

df = pd.DataFrame(data)
df

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

## 2. DataFrame with Specified Index Labels

In [4]:
exam_data = {
'name': ['Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'],
'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
'attempts':[1,3,2,3,2,3,1,1,2,1],
'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data,index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## 3. Select 'name' and 'score' Columns

In [5]:
df[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

## 4. Select 'name' and 'score' in rows 1,3,5,6

In [6]:
df.loc[df.index[[1,3,5,6]], ['name','score']]

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

## 5. Select rows where attempts > 2

In [7]:
df[df['attempts'] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

## 6. Count rows and columns

In [8]:
df.shape

(10, 4)

## 7. Rows with missing score

In [9]:
df[df['score'].isna()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

## 8. Score between 15 and 20

In [10]:
df[(df['score'] >= 15) & (df['score'] <= 20)]

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

## 9. Change score in row 'd'

In [11]:
df.loc['d','score'] = 11.5
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

## 10. Sum of attempts

In [12]:
df['attempts'].sum()

19

## 11. Mean of scores

In [13]:
df['score'].mean()

13.333333333333334

## 12. loc Example

In [14]:
df.loc[['a','b','c']]

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

## 13. iloc Example

In [15]:
df.iloc[:3]

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes